### ISSUE TITLE
Game Script - Nier: Replicant

### ISSUE THREAD

**Issue by ShadowVolt** [mathewthe2/Game2Text-GameScripts#2]
Attached below is the full Japanese text for Nier: Replicant.

This one was a royal pain in the rear to clean up compared to Automata. Since I didn't have a good way to automatically separate the Chinese lines from the Japanese ones, I had to painstakingly remove them line-by-line. (this clocks in at over 23k lines!!) There may still be some remnants of the Chinese left, as I didn't do a thorough second pass. I haven't tested it ingame for usability, but having finished the game in Japanese before, I can say that the vast majority of it is at least present. It will tend to favor individual sentences over entire blocks of text, so keep that in mind when using it. 

I have also included the raw files and my pre-merge cleaned files incase anyone else wants to take a crack at improving it later. (the novellas likely could use the most work, since they are sentence-by-sentence at the moment, which is not ideal for reading. they are in the talk_all section. also the letters/documents as well, forgot which file those were in.)

(edit 1: removed all identical lines, reducing length by around 5k lines.)

[Nier Replicant v2.txt](https://github.com/mathewthe2/Game2Text-GameScripts/files/6510740/Nier.Replicant.v2.txt)
[Nier Replicant - Raw+Edited.zip](https://github.com/mathewthe2/Game2Text-GameScripts/files/6505288/Nier.Replicant.-.Raw%2BEdited.zip)

**Comment by mathewthe2** [comment]
Good work. I don't have either games on PC to test them. 

Regarding scripts with multiple languages, it could be of use for instant game translation, but I haven't come up with a good format to parse them.

Right now I'm thinking of two ways.

One way is having them all in one text file separated by language 
```
JA:  お腹すいた。
EN: I'm hungry.
RU: Я голоден
JA: 何か食べようかな
...
```
This will be an easier format for the user since they need only to select one file. This however will increase the lines needed to be scanned and worsen matching performance, unless I first cache them into the system which in that case might slow down the app when loading matching scripts.

Another way would be to have multiple text files, and have each line correspond to its translation. This is a common format for programs displaying multiple languages. The drawback is that the user will have to prepare multiple text files and either import both of them to the app or create EN and JA folders to separate text from translation.

**Comment by ShadowVolt** [comment]
(Updated both script files by removing all duplicate lines.)

Having used this system extensively with Automata, I can safely say that it does not appreciate long script files over longer periods of time. There is a fairly severe slowdown after using it for a few hours. (to clarify, this is just a QoL issue, i'm finding this program extremely handy as a whole, and it has a fairly simple workaround.) This seems to happen faster with longer files, which is part of why I decided to remove everything other than the Japanese. 

I'm not sure of the exact cause, but I have a feeling that it is due to the number of log entries present in the webpage at once. It's possible that either setting a limit on how many past entries are displayed at a time in the log or adding a clear page button could help fix this particular slowdown, but I'm not positive. (This slowdown effects even the responsiveness of the main app when it gets bad enough, after a point I have to reboot the whole program.)

I'm just speculating here as I don't have any experience in this area, but maybe adding a system that somehow converts this into a kind of database (maybe sqlite, since that doesn't use a server/client model and can be embedded in the program?) could help with lookup performance, since they are typically designed to handle this kind of load. This would likely take a LOT of work, so maybe it could be investigated later after the app has gotten farther along.

---

But in any case, I do think it is a better idea to keep each language within separate files. It definitely is more work on the user/editor's end, but I don't feel that it is realistic to have them all in a single file. I'm also not sure how useful it would be to have more than one language in a single file for instant translation either. If the lines are appropriately numbered/tagged, referencing a separate file wouldn't be a problem. (this would be done before splitting the files during the editing stage for multi-lang scripts, and would likely be useful/easier if the database approach is used in the future)

I'm not saying that instant translation isn't useful as an idea at all, it definitely is; but this method has several drawbacks which make a game script hard to use for this in practice. The DeepL translator works very well in my experience, and I doubt many games that a script would be useful in have a literal line-to-line translation, futher limiting the usefulness. (For example, Automata's translation frequently diverges from the Japanese with the voiced dialogues, as it is a straight transcription of the english lines. Sometimes it breaks the lines in different places, resulting in inconsistent line numbering if used as-is.)

(Pardon the ramble, I tend to make large brain-dumps like this from time to time. Helps me get my thoughts straight when I put it into writing.)

**Comment by mathewthe2** [comment]
> how many past entries are displayed at a time in the log or adding a clear page button could help fix this particular slowdown, but I'm not positive. 

I've yet to implement logs clearing. 
- Browser logs clearing after certain amount (30-50) of logs. 
- Clearing image and audio files after 14 days

Another performance booster would be regional scanning, which prioritizes scans of nearby lines of the previous result and stops if the match reaches a certain confidence score. That has not been implemented.

In the meantime, you can always close the log window and reopen a new log window and see if that makes a difference to the performance. Since there is already a limit set (default 15) to how many logs would be reloaded when you reopen the log window, you can see if the performance issue persists..

There are human translations for games such as Animal Crossing which is why I proposed the idea, but you are right that there probably aren't a lot of games where people have gone through the effort of extracting their text and translating them.

**Comment by mathewthe2** [comment]
Clear browser log elements. Default maximum number of log elements to 30.
https://github.com/mathewthe2/Game2Text/commit/ca4dd82e52139ae0772702d9db20aa98fd16b9f4

**Comment by ShadowVolt** [comment]
Closing out this issue now, since the mentioned slowdown was dealt with and the script was mostly finalized.

**Comment by mathewthe2** [comment]
> This will be an easier format for the user since they need only to select one file. This however will increase the lines needed to be scanned and worsen matching performance, unless I first cache them into the system which in that case might slow down the app when loading matching scripts.

Since we already introduced script caching, this approach is probably the way to go. Nevertheless, we would have to define a format to differentiate between Japanese-only script files and script files with translations.
